services:
  vscode:
    image: vscwjm/myvscode:4.0.2-zh_CN-Real_Root
    privileged: true
    user: 0:0
    cap_add:
      - SYS_PTRACE
    ports:
      - 80:80
      - 81:81
      - 8080:8080
      - 3000:3000
      - 3001:3001
      - 3002:3002
      - 3003:3003
      - 3004:3004
      - 3005:3005
      - 3006:3006
    volumes:
      - date:/mnt/date

volumes:
  date:
    driver_opts:
      size: "5G"
